# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 12:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NigeriaLGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_0', models.IntegerField()),
                ('iso', models.CharField(max_length=3)),
                ('name_0', models.CharField(max_length=75)),
                ('id_1', models.IntegerField()),
                ('name_1', models.CharField(max_length=75)),
                ('id_2', models.IntegerField()),
                ('name_2', models.CharField(max_length=75)),
                ('varname_2', models.CharField(max_length=150)),
                ('nl_name_2', models.CharField(max_length=75)),
                ('hasc_2', models.CharField(max_length=15)),
                ('cc_2', models.CharField(max_length=15)),
                ('type_2', models.CharField(max_length=50)),
                ('engtype_2', models.CharField(max_length=50)),
                ('validfr_2', models.CharField(max_length=25)),
                ('validto_2', models.CharField(max_length=25)),
                ('remarks_2', models.CharField(max_length=100)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
